[cmake] Fix C0133 and C1041 on Windows (parallel compilation)
This commit fixes 2 occasional compile errors that happen when multiple
compliation jobs try to access the shared pdb file (which we need for the
precompiled headers).

fatal error C1041: cannot open program database 'debug\objs\vc120.pdb';
  if multiple CL.EXE write to the same .PDB file, please use /FS

This error is fixed by specifying the /FS option for the VS generator.

fatal error C1033: cannot open program database 'debug\objs\vc120.pdb'

This error is fixed by only setting the PDB_OUTPUT_DIRECTORY for targets
that use the precompiled header. The error was caused by the compilation
of JsonSchemaBuilder which happens in parallel to the pch compilation
since there is no dependency between the two targets.